apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rails-app
spec:
  source:
    repoURL: 'git@github.com:your-username/rails-devops-app.git'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  project: default
  syncPolicy:
    automated: {}
