apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  steps:
    - name: clone
      image: alpine/git
      script: |
        git clone https://github.com/your-username/rails-devops-app.git
