apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rails-pipeline
spec:
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
    - name: build-and-push
      taskRef:
        name: build-and-push
